version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - tradevision_network

  backend:
    build:
      context: ./backend
    container_name: tradevision_backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - MONGO_URI=mongodb://mongodb:27017/tradevision
    depends_on:
      - mongodb
    networks:
      - tradevision_network

networks:
  tradevision_network:
    driver: bridge

volumes:
  mongodb_data:
